language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r example/requirements-dev.txt
# command to run tests
script:
  - ./example/manage.py makemigrations
  - ./example/manage.py migrate
  - cd computedfields && coverage run --branch --source='.' ../example/manage.py test test_full
after_success: 'coveralls'