language: python
python:
  - "2.7"
  - "3.6"
  - "pypy"
  - "pypy3"
env:
  matrix:
      # test only Django 1.10, 1.11 and 2.0 (PY3 only)
    - DJANGO="Django<1.11"
    - DJANGO="Django<1.12"
    - DJANGO="Django<2.1"
matrix:
  exclude:
    - python: "3.6"
      env: DJANGO="Django<1.11"
    - python: "2.7"
      env: DJANGO="Django<2.1"
addons:
  apt:
    packages:
    - graphviz
install:
  - pip install "$DJANGO"
  - pip install -r example/requirements-travis.txt
script:
  - ./example/manage.py makemigrations
  - ./example/manage.py migrate
  - cd docs && make html
  - cd ../
  - coverage run --parallel-mode --branch --source='computedfields' ./example/manage.py test exampleapp
  - coverage run --parallel-mode --branch --source='computedfields' ./example/manage.py test test_full
  - coverage combine
  - coverage report
after_success: coveralls