language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
addons:
  apt:
    packages:
    - graphviz
install:
  - pip install -r example/requirements-dev.txt
script:
  - ./example/manage.py makemigrations
  - ./example/manage.py migrate
  - cd docs && make html
  - cd ../computedfields && coverage run --branch --source='.' ../example/manage.py test test_full
  - coverage report
after_success: coveralls