# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  django_22:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - uses: kamiazya/setup-graphviz@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "Django~=2.2"
        pip install -r example/requirements-travis.txt
    - name: Setup DB
      run: |
        ./example/manage.py makemigrations
        ./example/manage.py migrate
    - name: Build docs
      run: |
        cd docs && make html
        cd ../
    - name: Run tests
      run: |
        coverage run --parallel-mode --branch --source='computedfields' ./example/manage.py test exampleapp
        coverage run --parallel-mode --branch --source='computedfields' ./example/manage.py test test_full
        coverage combine
        coverage report
    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        flag-name: run-django22-${{ matrix.python-version }}
        parallel: true

  django_32:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - uses: kamiazya/setup-graphviz@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "Django~=3.2"
        pip install -r example/requirements-travis.txt
    - name: Setup DB
      run: |
        ./example/manage.py makemigrations
        ./example/manage.py migrate
    - name: Build docs
      run: |
        cd docs && make html
        cd ../
    - name: Run tests
      run: |
        coverage run --parallel-mode --branch --source='computedfields' ./example/manage.py test exampleapp
        coverage run --parallel-mode --branch --source='computedfields' ./example/manage.py test test_full
        coverage combine
        coverage report
    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        flag-name: run-django32-${{ matrix.python-version }}
        parallel: true

  finish:
    needs: [django_22, django_32]
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
